# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Seungkyu Kim
title: AI Researcher
email: aszass5387@gmail.com
website: www.github.com/BanDoong/

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
github_username:  BanDoong
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: seungkyu-kim-87b724189
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be


# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/kim_profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Seungkyu and I'm currently studying AI for Computer vision. Now I'm looking for a job.

  I am most skilled in: <mark>Pytorch</mark> and <mark>Computer Vision</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Multimodality Leanring for Early Diagnosis of Alzheimer's Disease
        #link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  BanDoong/Diagnosis-Alzheimer-s-Disease
            icon: fab fa-github
            url: github.com/BanDoong/Diagnosis-Alzheimer-s-Disease
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: > 
          Currently Ongoing Project. Will be submitted to Journal.
        description: | # this will include new lines to allow paragraphs
          Alzheimer's Disease is a severe problem in the world. There is no treatment for stopping or reverse to healthy. Therefore, Early Diagnosis is Crucial. I developed new model for Early Diagnosis of Alzheimer's Disease using Muli-Modal Image Data.
      - layout: top-middle
        title: Water Boundary Segmentation in Satellite Images.
        additional_links:
          - title:  BanDoong/Segmentation_for_SAR_Image
            icon: fab fa-github
            url: github.com/BanDoong/Segmentation_for_SAR_Image
        quote: > 
          Comparative Study of Deep Learning Model for Semantic Segmentation of Water System in SAR Images of KOMPSAT-5, MJ Kim, SK Kim, DH Lee, JK Gahm, Journal of Korea Multimedia Society, Vol 25., pp. 206-214, 2022
        description: | 
          In order to measure the extent of damage from floods and droughts, satellite images are used. For efficiently identify extent of the floods and droughts, We applied various Deep Learning Model for semantic segmentation, and compared models. This Research was submitted to Journal.
      - layout: top-middle
        title: Self-Supervised Learning for Alzheimer's Disease
        additonal_links:
          - title: BanDoong/Self-Supervised-Learning-for-Early-AD
            icon: fab fa-github
            url: github.com/BanDoong/Self-Supervised-Learning-for-Early-AD
        description: | 
          In medical feild, There are relatively few labeled image data. Therefore, Learning without Label is crucial. I used SimCLR, BYOL to Self-Supervised Leanring for Early Diagnosis of Alzheimer's Disease.
      - layout: top-middle
        title: Prediction of Pawpularity (Attractiveness of Pictures)
        additional links:
          - title: BanDoong/PetFinder-Prediction-Pawpularity
            icon: fab fa-github
            url: https://github.com/BanDoong/PetFinder-Prediction-Pawpularity
        description: | 
          PetFinder is Malaysia's leading animal welfare platform and they adopt animals. This project aim to make animal happily adopt using predict how much Pictures are attractive. Therefore, I used ViT, ResNet50, EfficientNet and ensemble EfficientNet and ViT.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: LG Electronics
        link: www.lge.co.kr
        # link_text: boringcompany.com
        sub_title: Junior Researcher
        caption: Jan. 2020 - Feb. 2021

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Pusan National University
        caption: 2013.03 - 2019.02
        sub_title: BS Mechanical Engineering
#    layout: list
#    content:
      - layout: top-middle
        title: Pusan National University
        caption: 2021.03 - Present (Expected Graduation Date 2023.02)
        sub_title: MS Computer Science

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
#      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
